---
version: "2.1"

services:
  consul:
    image: ${IMAGE_NAME:-pdouble16/autopilotpattern-consul:latest}
    environment:
      CONSUL: consul
    dns: 127.0.0.1
    mem_limit: 64M
    cpu_quota: 6250
    #cpus: '0.0625'
    ports:
      - 8500
